# Generated by Django 4.1.4 on 2022-12-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.PositiveIntegerField()),
                ('smell', models.CharField(choices=[('клубника', 'клубника'), ('лаванда', 'лаванда'), ('апельсин', 'апельсин'), ('имбирное печенье', 'имбирное печенье')], max_length=50)),
                ('wicks', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.PositiveIntegerField()),
                ('color', models.CharField(choices=[('розовый', 'розовый'), ('фиолетовый', 'фиолетовый'), ('бежевый', 'бежевый'), ('оранжевый', 'оранжевый')], max_length=50)),
                ('material', models.CharField(choices=[('стекло', 'стекло'), ('керамика', 'керамика'), ('пластик', 'пластик')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Soap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.PositiveIntegerField()),
                ('color', models.CharField(choices=[('жёлтый', 'жёлтый'), ('фиолетовый', 'фиолетовый'), ('голубой', 'голубой'), ('зелёный', 'зелёный'), ('красный', 'красный')], max_length=50)),
                ('smell', models.CharField(choices=[('клубника', 'клубника'), ('лаванда', 'лаванда'), ('апельсин', 'апельсин'), ('имбирное печенье', 'имбирное печенье')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
