# Generated by Django 4.1.4 on 2022-12-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candles',
            name='link',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
    ]
