# Generated by Django 4.1.4 on 2023-01-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_candles_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candles',
            options={'verbose_name': 'Свеча', 'verbose_name_plural': 'Свечи'},
        ),
        migrations.AlterModelOptions(
            name='cups',
            options={'verbose_name': 'Чашка', 'verbose_name_plural': 'Чашки'},
        ),
        migrations.AlterModelOptions(
            name='soap',
            options={'verbose_name': 'Мыло', 'verbose_name_plural': 'Мыло'},
        ),
        migrations.AddField(
            model_name='candles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='cups',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='soap',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
